# Generated by Django 3.1.6 on 2021-03-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_lecturer_covers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='covers',
            new_name='cover',
        ),
    ]
