# Generated by Django 3.1.6 on 2021-03-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20210317_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='covers',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cover',
            new_name='avatar',
        ),
    ]
