# Generated by Django 3.1.6 on 2021-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='execution_time_sec',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
